<?php

namespace App\Exports;

use App\Models\Admin;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;

class AdminExport implements FromCollection, WithHeadings, WithMapping, WithEvents
{
    public function collection()
    {
        return Admin::query()
            ->orderBy('full_name')
            ->get();
    }

    public function headings(): array
    {
        return [
            'ID',
            'Full Name',
            'Email',
            'Username',
            'Role',
            'Created At',
            'Updated At',
        ];
    }

    public function map($admin): array
    {
        return [
            $admin->id,
            $admin->full_name,
            $admin->email,
            $admin->username,
            'Staff', // All admins are staff
            $admin->created_at->format('Y-m-d H:i:s'),
            $admin->updated_at->format('Y-m-d H:i:s'),
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();
                $lastRow = $sheet->getHighestRow();
                $footerRow = $lastRow + 2;

                // Add footer text with underlined RMD - RMMS
                $cell = $sheet->getCell('A' . $footerRow);
                $richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
                $richText->createText('This is an automated report generated by ');
                $underlined = $richText->createTextRun('RMD - RMMS');
                $underlined->getFont()->setUnderline(true);
                $cell->setValue($richText);
                $sheet->getStyle('A' . $footerRow)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
                $sheet->mergeCells('A' . $footerRow . ':' . $sheet->getHighestColumn() . $footerRow);
            },
        ];
    }
}

