<?php

namespace App\Exports;

use App\Models\InventoryItem;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;

class InventoryExport implements FromCollection, WithHeadings, WithMapping, WithEvents
{
    public function collection()
    {
        return InventoryItem::query()
            ->orderBy('name')
            ->get();
    }

    public function headings(): array
    {
        return [
            'ID',
            'Name',
            'Category',
            'Description',
            'Total Quantity',
            'Available Quantity',
            'Type',
            'Status',
            'Location',
            'Brand',
            'Model',
            'Serial Number',
            'Unit Price',
            'Purchase Date',
            'Created At',
        ];
    }

    public function map($item): array
    {
        return [
            $item->id,
            $item->name,
            $item->category ?? 'N/A',
            $item->description ?? '',
            $item->total_quantity,
            $item->available_quantity,
            ucfirst($item->type),
            ucfirst($item->status),
            $item->location ?? 'N/A',
            $item->brand ?? '',
            $item->model ?? '',
            $item->serial_number ?? '',
            $item->unit_price ?? 0,
            $item->purchase_date ? $item->purchase_date->format('Y-m-d') : '',
            $item->created_at->format('Y-m-d H:i:s'),
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();
                $lastRow = $sheet->getHighestRow();
                $footerRow = $lastRow + 2;

                // Add footer text with underlined RMD - RMMS
                $cell = $sheet->getCell('A' . $footerRow);
                $richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
                $richText->createText('This is an automated report generated by ');
                $underlined = $richText->createTextRun('RMD - RMMS');
                $underlined->getFont()->setUnderline(true);
                $cell->setValue($richText);
                $sheet->getStyle('A' . $footerRow)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
                $sheet->mergeCells('A' . $footerRow . ':' . $sheet->getHighestColumn() . $footerRow);
            },
        ];
    }
}

