<?php

namespace App\Exports;

use App\Models\BorrowTransaction;
use Carbon\Carbon;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;

class TransactionsExport implements FromCollection, WithHeadings, WithMapping, WithEvents
{
    protected $startDate;
    protected $endDate;

    public function __construct($startDate, $endDate)
    {
        $this->startDate = $startDate;
        $this->endDate = $endDate;
    }

    public function collection()
    {
        return BorrowTransaction::with(['user', 'inventoryItem'])
            ->whereBetween('borrow_date', [$this->startDate, $this->endDate])
            ->orderBy('borrow_date', 'desc')
            ->get();
    }

    public function headings(): array
    {
        return [
            'Transaction ID',
            'Borrower Name',
            'Borrower ID',
            'Item Name',
            'Quantity',
            'Borrow Date',
            'Expected Return Date',
            'Actual Return Date',
            'Status',
            'Purpose',
            'Location',
            'Notes',
            'Approved By',
            'Approved At',
        ];
    }

    public function map($transaction): array
    {
        // Get borrower name - try user relationship first, then fall back to borrower_name
        $borrowerName = 'N/A';
        $borrowerId = 'N/A';

        if ($transaction->user) {
            $borrowerName = trim(
                $transaction->user->first_name . ' ' .
                ($transaction->user->middle_name ?? '') . ' ' .
                $transaction->user->last_name
            );
            $borrowerId = $transaction->user->id_number ?? $transaction->user->student_id ?? $transaction->user->emp_id ?? 'N/A';
        } elseif ($transaction->borrower_name) {
            $borrowerName = $transaction->borrower_name;
            $borrowerId = $transaction->borrower_id_number ?? 'N/A';
        }

        return [
            $transaction->transaction_id,
            $borrowerName,
            $borrowerId,
            $transaction->inventoryItem->name ?? 'N/A',
            $transaction->quantity,
            $transaction->borrow_date->format('Y-m-d'),
            $transaction->expected_return_date->format('Y-m-d'),
            $transaction->actual_return_date ? $transaction->actual_return_date->format('Y-m-d') : '',
            ucfirst($transaction->status),
            $transaction->purpose ?? '',
            $transaction->location ?? '',
            $transaction->notes ?? '',
            $transaction->approved_by ?? '',
            $transaction->approved_at ? Carbon::parse($transaction->approved_at)->format('Y-m-d H:i:s') : '',
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();
                $lastRow = $sheet->getHighestRow();
                $footerRow = $lastRow + 2;

                // Add footer text with underlined RMD - RMMS
                $sheet->setCellValue('A' . $footerRow, 'This is an automated report generated by RMD - RMMS');
                $sheet->getStyle('A' . $footerRow)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
                $sheet->mergeCells('A' . $footerRow . ':' . $sheet->getHighestColumn() . $footerRow);

                // Underline only "RMD - RMMS" part using rich text
                $cell = $sheet->getCell('A' . $footerRow);
                $cell->setValue('This is an automated report generated by ');
                $richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
                $richText->createText('This is an automated report generated by ');
                $underlined = $richText->createTextRun('RMD - RMMS');
                $underlined->getFont()->setUnderline(true);
                $cell->setValue($richText);
            },
        ];
    }
}

