<?php

namespace App\Exports;

use App\Models\User;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;

class UsersExport implements FromCollection, WithHeadings, WithMapping, WithEvents
{
    protected $type;

    public function __construct($type = 'all')
    {
        $this->type = $type;
    }

    public function collection()
    {
        $query = User::query();
        if ($this->type !== 'all') {
            $query->where('type', $this->type);
        }
        return $query->orderBy('last_name')->get();
    }

    public function headings(): array
    {
        return [
            'ID',
            'ID Number',
            'First Name',
            'Middle Name',
            'Last Name',
            'Full Name',
            'Email',
            'Contact Number',
            'Type',
            'Department',
            'Course',
            'Year Level',
            'Status',
            'Created At',
        ];
    }

    public function map($user): array
    {
        return [
            $user->id,
            $user->id_number,
            $user->first_name,
            $user->middle_name ?? '',
            $user->last_name,
            trim($user->first_name . ' ' . ($user->middle_name ?? '') . ' ' . $user->last_name),
            $user->email,
            $user->contact_number,
            ucfirst($user->type),
            $user->department,
            $user->course ?? '',
            $user->year_level ?? '',
            ucfirst($user->status),
            $user->created_at->format('Y-m-d H:i:s'),
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();
                $lastRow = $sheet->getHighestRow();
                $footerRow = $lastRow + 2;

                // Add footer text with underlined RMD - RMMS
                $cell = $sheet->getCell('A' . $footerRow);
                $richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
                $richText->createText('This is an automated report generated by ');
                $underlined = $richText->createTextRun('RMD - RMMS');
                $underlined->getFont()->setUnderline(true);
                $cell->setValue($richText);
                $sheet->getStyle('A' . $footerRow)->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
                $sheet->mergeCells('A' . $footerRow . ':' . $sheet->getHighestColumn() . $footerRow);
            },
        ];
    }
}

