<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .stats {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            padding: 10px;
            background: #f5f5f5;
            border: 1px solid #ddd;
            text-align: center;
            width: 25%;
        }
        .stat-box strong {
            display: block;
            font-size: 18px;
            color: #333;
        }
        .stat-box span {
            font-size: 11px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #333;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 6px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ $date }}</p>
        <p>RMD-GSU Inventory Management System</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <strong>{{ $stats['total_items'] }}</strong>
            <span>Total Items</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['total_quantity'] }}</strong>
            <span>Total Quantity</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['available_quantity'] }}</strong>
            <span>Available</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['low_stock_count'] }}</strong>
            <span>Low Stock Items</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Category</th>
                <th>Type</th>
                <th>Total Qty</th>
                <th>Available</th>
                <th>Status</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            @foreach($inventory as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->category ?? 'N/A' }}</td>
                <td>{{ ucfirst($item->type) }}</td>
                <td>{{ $item->total_quantity }}</td>
                <td>{{ $item->available_quantity }}</td>
                <td>{{ ucfirst($item->status) }}</td>
                <td>{{ $item->location ?? 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an automated report generated by <span style="text-decoration: underline;">RMD - RMMS</span></p>
    </div>
</body>
</html>

