<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .stats {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            padding: 8px;
            background: #f5f5f5;
            border: 1px solid #ddd;
            text-align: center;
            width: 20%;
        }
        .stat-box strong {
            display: block;
            font-size: 16px;
            color: #333;
        }
        .stat-box span {
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 10px;
        }
        th {
            background-color: #333;
            color: white;
            padding: 6px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 5px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Period: {{ $start_date }} to {{ $end_date }}</p>
        <p>Generated on: {{ $date }}</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <strong>{{ $stats['total_returns'] }}</strong>
            <span>Total Returns</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['excellent'] }}</strong>
            <span>Excellent</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['good'] }}</strong>
            <span>Good</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['fair'] }}</strong>
            <span>Fair</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['damaged'] }}</strong>
            <span>Damaged</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Return Date</th>
                <th>Borrower</th>
                <th>Item</th>
                <th>Condition</th>
                <th>Received By</th>
                <th>Damage Fee</th>
            </tr>
        </thead>
        <tbody>
            @foreach($returns as $return)
            <tr>
                <td>{{ $return->return_date->format('Y-m-d') }}</td>
                <td>
                    @if($return->borrowTransaction && $return->borrowTransaction->user)
                        {{ trim($return->borrowTransaction->user->first_name . ' ' . ($return->borrowTransaction->user->middle_name ?? '') . ' ' . $return->borrowTransaction->user->last_name) }}
                    @elseif($return->borrowTransaction && $return->borrowTransaction->borrower_name)
                        {{ $return->borrowTransaction->borrower_name }}
                    @else
                        N/A
                    @endif
                </td>
                <td>{{ $return->borrowTransaction->inventoryItem->name ?? 'N/A' }}</td>
                <td>{{ ucfirst($return->condition) }}</td>
                <td>{{ $return->received_by }}</td>
                <td>₱{{ number_format($return->damage_fee, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an automated report generated by <span style="text-decoration: underline;">RMD - RMMS</span></p>
    </div>
</body>
</html>

