<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .stats {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            padding: 8px;
            background: #f5f5f5;
            border: 1px solid #ddd;
            text-align: center;
            width: 20%;
        }
        .stat-box strong {
            display: block;
            font-size: 16px;
            color: #333;
        }
        .stat-box span {
            font-size: 10px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 10px;
        }
        th {
            background-color: #333;
            color: white;
            padding: 6px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 5px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Type: {{ ucfirst($type) }}</p>
        <p>Generated on: {{ $date }}</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <strong>{{ $stats['total_users'] }}</strong>
            <span>Total Users</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['students'] }}</strong>
            <span>Students</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['employees'] }}</strong>
            <span>Employees</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['active'] }}</strong>
            <span>Active</span>
        </div>
        <div class="stat-box">
            <strong>{{ $stats['inactive'] }}</strong>
            <span>Inactive</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID Number</th>
                <th>Name</th>
                <th>Email</th>
                <th>Type</th>
                <th>Department</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id_number }}</td>
                <td>{{ $user->first_name }} {{ $user->middle_name ?? '' }} {{ $user->last_name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ ucfirst($user->type) }}</td>
                <td>{{ $user->department }}</td>
                <td>{{ ucfirst($user->status) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an automated report generated by <span style="text-decoration: underline;">RMD - RMMS</span></p>
    </div>
</body>
</html>

